sudo: required
dist: trusty
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libprotobuf-dev', 'protobuf-compiler']

compiler:
  - gcc

language: cpp

script:
    cd floyd && make
